### ISSUE TITLE
部署了一下，附地址

### ISSUE THREAD

**Issue by Monster12138** [sangyx/nCoV-Map#2]
使用@sangyx 的代码部署了一下，[地址](http://39.108.227.206:8088)
pc端很不错，移动端适配还有点问题

**Comment by sangyx** [comment]
我前端不是很懂，直接套的模板。请问可以把这个地址放在readme中吗？

**Comment by Monster12138** [comment]
可以

**Comment by BigtoC** [comment]
地图没有显示出来。
浏览器是手机版的Chrome
![Screenshot_20200127-133114](https://user-images.githubusercontent.com/33389684/73152141-9a739a80-4109-11ea-89cf-3644467f19cc.jpg)

**Comment by sangyx** [comment]
> 地图没有显示出来。
> 浏览器是手机版的Chrome
> ![Screenshot_20200127-133114](https://user-images.githubusercontent.com/33389684/73152141-9a739a80-4109-11ea-89cf-3644467f19cc.jpg)

用电脑打开，手机显示有问题
