### ISSUE TITLE
数据不准确

### ISSUE THREAD

**Issue by bytedo** [sangyx/nCoV-Map#5]

**Comment by sangyx** [comment]
因为数据接口中途变更过，所以开始版本的数据显示并不准确，已修复

**Comment by MLPythoner** [comment]
> 因为数据接口中途变更过，所以开始版本的数据显示并不准确，已修复

请问地图数据大概有多长时间的滞后，目前和网上对比了一下，青海、内蒙等等数据是不对等。

**Comment by sangyx** [comment]
> > 因为数据接口中途变更过，所以开始版本的数据显示并不准确，已修复
> 
> 请问地图数据大概有多长时间的滞后，目前和网上对比了一下，青海、内蒙等等数据是不对等。

最新的代码展示的最新数据是准确，滞后在30min内。ctrl+f5可以刷新页面获取最新数据。之前数据不准确是因为从数据接口拿到的一些数据有问题
